[package]
name = "corgi-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Core CODEOWNERS reconciliation engine for CORGI"
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
camino.workspace = true
git2.workspace = true
ignore.workspace = true
regex.workspace = true
tempfile.workspace = true
thiserror.workspace = true
