[package]
name = "corgi"
version = "0.1.1"
edition = "2024"
rust-version = "1.95"
description = "CORGI: CodeOwners Reconciler for Git Integrity"
license = "MIT"
authors = ["Samuel Giffard <samuel@giffard.co>"]
repository = "https://github.com/Mulugruntz/codeowners-corgi"
readme = "README.md"

[dependencies]
camino = "1.1"
clap = { version = "4.5", features = ["derive"] }
git2 = { version = "0.21.0", default-features = false }
ignore = "0.4"
regex = "1.11"
tempfile = "3.20"
thiserror = "2.0"

[dev-dependencies]
assert_cmd = "2.0"
indoc = "2.0"
predicates = "3.1"
tempfile = "3.20"
